### PR TITLE
MARP-626 Fix for Dev Fail on Market-Monitor

### PR DESCRIPTION
**Pull request by phhung-axonivy**

### CODE REVIEW

**Comment by phhung-axonivy** [comment]
Hi @ivy-rew 
Could you please review this pull request?

**Review by ivy-rew — APPROVED** [review]
looks good; would be great if we can make the 'dev' pipeline compliant with the ci.

**Comment by phhung-axonivy** [comment]
Hi @ivy-rew 
Could you add comment on the place that is not so good?
I am willing to change it.

**Comment by ivy-rew** [comment]
Hi @phhung-axonivy 
we found other builds with the same error yesterday, they are related to changes we have done in the dev-workflow-ui ... master no longer offers the same functionality to pickup tasks, so the web-test would have to be adjusted.
However, this is not related to you story, you are free to merge as is. And I leave a note here for the current maintainer of the dev-workflow-ui @jackra1n, so he may invest on fixing this test.

**Pull request merged**
