### PR TITLE
Dev pipeline

### PR DESCRIPTION
**Pull request by ivy-rew**

### CODE REVIEW

**Comment by ivy-rew** [comment]
I'd merge it as and decide later whether we need a distinct master branch, targeting 11.2 due to the incompatible IFileAcess

**Review by ivy-lli — APPROVED** [review]
I think we should anyway create a new project for each aspose lib.
One for word one for excel etc...
Then the doc-factory wouldn't be 100MB if you only need some word stuff e.g

**Comment by ivy-rew** [comment]
> I think we should anyway create a new project for each aspose lib. One for word one for excel etc... Then the doc-factory wouldn't be 100MB if you only need some word stuff e.g

yes, I agree. Maybe we could even make a simple apprentice refurbishment project out of this.
- split the projects
- address the most obvious code flaws

**Comment by ivy-lli** [comment]
Or an octopus project? 🐙

**Pull request merged**
